# Generated by Django 4.1.7 on 2023-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="rules",),
        migrations.AddField(
            model_name="event",
            name="rules",
            field=models.ManyToManyField(blank=True, null=True, to="events.rules"),
        ),
    ]
